// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "MainCharacter":return img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b 8 8 f f f f 8 f f f f 8 f f f 
8 8 8 f f f f 8 f f f f 8 8 . . 
8 8 8 f f f f 8 f f f f 8 . . . 
. . e e e e e . e e e e e . . . 
`;
            case "image2":
            case "MainCharacter0":return img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b 8 8 f f f f 8 f f f f 8 f f f 
8 8 8 f f f f 8 f f f f 8 8 . . 
8 8 8 f f f f 8 f f f f 8 . . . 
. . e e e e e . e e e e e . . . 
`;
            case "image3":
            case "Enemy 1":return img`
. . . . . . . . . . . . . . . . 
. d . . d . . . . . d . . . . . 
. d . . d d . . . d d . . . . . 
d d d . f f f f f f f . . . . . 
d e d . f 2 f f f 2 f . . . . . 
. e . . f f f f f f f . . . . . 
. e . . f f e e e f f . . . . . 
. e . . . f f f f f . . . . . . 
. e . . . . f f f . . . . . . . 
. e . f f f f f f f f f . . . . 
. f f f f f f f f f f f f . . . 
. e f f f f f f f f f f . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
`;
            case "image4":
            case "MainCharacter1":return img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b 8 8 f f f f 8 f f f f 8 f f f 
8 8 8 f f f f 8 f f f f 8 8 . . 
8 8 8 f f f f 8 f f f f 8 . . . 
. . e e e e e . e e e e e . . . 
`;
            case "image5":
            case "Enemy 4":return img`
. . . . 2 4 4 4 2 . . . . . . . 
. . . . 4 2 4 2 4 . . . . . . . 
. . . . 4 4 4 4 4 . . . . . . . 
4 . . . 4 e e e 4 . . . . 4 . . 
4 4 . . f f f f f . . . 4 4 . . 
. 4 . f f f f f f f . 4 4 . . . 
. 4 4 f f f f f f f 4 4 . . . . 
. . . f f f f f f f . . . . . . 
. . . f f f f f f f . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c . c c c . . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "Enemy 3":return img`
................................
...44444........................
..44eee44.......................
..4eeeee4.......................
.44e2e2e44......................
...eeeee.....fb.................
...eefee..eefbb.................
ee...e...eefbbb.................
.ee22222eef.....................
...22222.f......................
...22222........................
...22222........................
...ff.ff........................
..ff...ff.......................
.ff.....ff......................
.f.......ff.....................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image7":
            case "Bossman":return img`
........................b.......
.........555.55.55.....bbb......
.........525552552....bb6bb.....
.........555555555....bb6bb.....
..........1111111.....b666b.....
..........11211121....bb6bb.....
.........112221222....bb6bb.....
.........111211121....bb6bb.....
.........111111111....b666b.....
.........11f1f1f11....bb6bb.....
.........111fff11.....bb6bb.....
............111.......b666b.....
.........ddddfddd......666......
.......ffddfffffdffffffeee......
.....ffffddddfdddffffffeee......
.eeeeeff.ddddfddd......eee......
.eeeeef..ddddfddd...............
eeeeeeee.ddfffffd...............
eeeeeeee.ddddfddd...............
eeeeeeee.ddddfdddd..............
eeeeeeeedddddfdddd..............
eeeeeeeedddddddddd..............
.eeeee..dddffffddd..............
.eeeee...ffffffff...............
.........fffffffff..............
........fffff.fffff.............
........fffff.ffffff............
........ffff...fffff............
........ffff....ffff............
.....ffffff......ffffff.........
.....ffffff......ffffff.........
.....ffffff......ffffff.........
`;
            case "image8":
            case "Girlfriend":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 5 5 5 5 5 5 . . . . . . 
. . . . 5 e e e e 5 . . . . . . 
. . . 5 5 e 1 e 1 5 5 . . . . . 
. . . 5 5 e e e e 5 5 . . . . . 
. . . 5 5 e e f e 5 5 5 . . . . 
. . 5 5 5 a a a a . 5 5 . . . . 
. . 5 5 a a a a a a 5 . . . . . 
. . . 5 a a a a a a 5 5 . . . . 
. . . a a a a a a a a . . . . . 
. . . a a a a a a a a . . . . . 
. . a a a a a a a a a a . . . . 
. . a a a a a a a a a a . . . . 
. a a a a a a a a a a a a . . . 
. . . f f . . . f f . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim1":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. d . . d . . . . . d . . . . . 
. d . . d d . . . d d . . . . . 
d d d . f f f f f f f . . . . . 
d e d . f 2 f f f 2 f . . . . . 
. e . . f f f f f f f . . . . . 
. e . . f f e e e f f . . . . . 
. e . . . f f f f f . . . . . . 
. e . . . . f f f . . . . . . . 
. e . f f f f f f f f f . . . . 
. f f f f f f f f f f f f . . . 
. e f f f f f f f f f f . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . d . . . . . d . . . . . 
. . . . d d . . . d d . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f 2 f f f 2 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f e e e f f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
. d d . f f f f f f f f . . . . 
d d d e e e e e e e e e e e . . 
. d d . f f f f f f f f . . . . 
. . . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. d . . d . . . . . d . . . . . 
. d . . d d . . . d d . . . . . 
d d d . f f f f f f f . . . . . 
d e d . f 2 f f f 2 f . . . . . 
. e . . f f f f f f f . . . . . 
. e . . f f e e e f f . . . . . 
. e . . . f f f f f . . . . . . 
. e . . . . f f f . . . . . . . 
. e . f f f f f f f f f . . . . 
. f f f f f f f f f f f f . . . 
. e f f f f f f f f f f . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. e . . f f . . f f . . . . . . 
. . . . f f . . f f . . . . . . 
`];
            case "myAnim2":
            case "anim4":return [img`
. . . . 2 4 4 4 2 . . . . . . . 
. . . . 4 2 4 2 4 . . . . . . . 
. . . . 4 4 4 4 4 . . . . . . . 
4 . . . 4 e e e 4 . . . . 4 . . 
4 4 . . f f f f f . . . 4 4 . . 
. 4 . f f f f f f f . 4 4 . . . 
. 4 4 f f f f f f f 4 4 . . . . 
. . . f f f f f f f . . . . . . 
. . . f f f f f f f . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c . c c c . . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . 2 4 4 4 2 . . . . . . . 
. . . . 4 2 4 2 4 . . . . . . . 
. . . . 4 4 4 4 4 . . . . . . . 
. . . . 4 e e e 4 . . . . . . . 
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
4 4 4 f f f f f f f 4 4 4 4 4 . 
. . . f f f f f f f . . . . . . 
. . . f f f f f f f . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c . c c c . . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . 2 4 4 4 2 . . . . . . . 
. . . . 4 2 4 2 4 . . 4 4 4 . . 
. . . . 4 4 4 4 4 . . . . 4 4 . 
. . . . 4 e e e 4 . . . . . 4 . 
. . . . f f f f f . . . . . 4 . 
. . . f f f f f f f . . . 4 4 . 
4 4 4 f f f f f f f 4 4 4 4 . . 
4 4 . f f f f f f f . . . . . . 
4 . . f f f f f f f . . . . . . 
4 4 . c c c c c c c . . . . . . 
. . 4 c c c c c c c . . . . . . 
. . . c c c . c c c . . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . 2 4 4 4 2 . . . . . . . 
. . . . 4 2 4 2 4 . . . . . . . 
. . . . 4 4 4 4 4 . . . . . . . 
4 . . . 4 e e e 4 . . . . 4 . . 
4 4 . . f f f f f . . . 4 4 . . 
. 4 . f f f f f f f . 4 4 . . . 
. 4 4 f f f f f f f 4 4 . . . . 
. . . f f f f f f f . . . . . . 
. . . f f f f f f f . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c c c c c . . . . . . 
. . . c c c . c c c . . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . e e e e . e e e e . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "Boss Animation":
            case "anim1":return [img`
........................b.......
.........555.55.55.....bbb......
.........525552552....bb6bb.....
.........555555555....bb6bb.....
..........1111111.....b666b.....
..........11211121....bb6bb.....
.........112221222....bb6bb.....
.........111211121....bb6bb.....
.........111111111....b666b.....
.........11f1f1f11....bb6bb.....
.........111fff11.....bb6bb.....
............111.......b666b.....
.........ddddfddd......666......
.......ffddfffffdffffffeee......
.....ffffddddfdddffffffeee......
.eeeeeff.ddddfddd......eee......
.eeeeef..ddddfddd...............
eeeeeeee.ddfffffd...............
eeeeeeee.ddddfddd...............
eeeeeeee.ddddfdddd..............
eeeeeeeedddddfdddd..............
eeeeeeeedddddddddd..............
.eeeee..dddffffddd..............
.eeeee...ffffffff...............
.........fffffffff..............
........fffff.fffff.............
........fffff.ffffff............
........ffff...fffff............
........ffff....ffff............
.....ffffff......ffffff.........
.....ffffff......ffffff.........
.....ffffff......ffffff.........
`, img`
................................
.........555.55.55..............
.........525552552..............
.........555555555..............
..........1111111...............
..........11211121..............
.........112221222..............
.........111211121..............
.........111111111..............
.........11f1f1f11..............
.........111fff11...............
............111..............bbb
.........ddddfddd...........b6bb
.......ffddfffffdff......b6bb66b
.....ffffddddfdddffff...bbb666bb
.eeeeeff.ddddfddd..ffff.bb66b6b.
.eeeeef..ddddfddd....ffe666bbb..
eeeeeeee.ddfffffd....eeebbb6....
eeeeeeee.ddddfddd.......bbb.....
eeeeeeee.ddddfdddd..............
eeeeeeeedddddfdddd..............
eeeeeeeedddddddddd..............
.eeeee..dddffffddd..............
.eeeee...ffffffff...............
.........fff...ffff.............
.........ffff..ffffff...........
.........ffff..fffffff..........
.........fffff..fffffff.........
..........fffff...ffffff........
...........fffff...ffffff.......
............ffff....fffff.......
............ffff.....ffff.......
`, img`
................................
.........555.55.55..............
.........525552552..............
.........555555555..............
..........1111111...............
..........12221222..............
.........112221222..............
.........112221222..............
.........111111111..............
.........11f1f1f11..............
.........111fff11...............
............111..............bbb
.........ddddfddd...........b6bb
.......ffddfffffdff......b6bb66b
.....ffffddddfdddffff...bbb666bb
.eeeeeff.ddddfddd..ffff.bb66b6b.
.eeeeef..ddddfddd....ffe666bbb..
eeeeeeee.ddfffffd....eeebbb6....
eeeeeeee.ddddfddd.......bbb.....
eeeeeeee.ddddfdddd..............
eeeeeeeedddddfdddd..............
eeeeeeeedddddddddd..............
.eeeee..dddffffddd..............
.eeeee...ffffffff...............
.........ffffffffff.............
........fffffffffffff...........
........ffffffffffffff..........
........fff.....fffffff.........
.......fff........ffffff........
.......fff.........ffffff.......
......ffff..........fffff.......
......fff............ffff.......
`, img`
........................b.......
.........555.55.55.....bbb......
.........525552552....bb6bb.....
.........555555555....bb6bb.....
..........1111111.....b666b.....
..........11211121....bb6bb.....
.........112221222....bb6bb.....
.........111211121....bb6bb.....
.........111111111....b666b.....
.........11f1f1f11....bb6bb.....
.........111fff11.....bb6bb.....
............111.......b666b.....
.........ddddfddd......666......
.......ffddfffffdffffffeee......
.....ffffddddfdddffffffeee......
.eeeeeff.ddddfddd......eee......
.eeeeef..ddddfddd...............
eeeeeeee.ddfffffd...............
eeeeeeee.ddddfddd...............
eeeeeeee.ddddfdddd..............
eeeeeeeedddddfdddd..............
eeeeeeeedddddddddd..............
.eeeee..dddffffddd..............
.eeeee...ffffffff...............
.........fffffffff..............
........fffff.fffff.............
........fffff.ffffff............
........ffff...fffff............
........ffff....ffff............
.....ffffff......ffffff.........
.....ffffff......ffffff.........
.....ffffff......ffffff.........
`];
            case "Player moving":
            case "anim5":return [img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b 8 8 f f f f 8 f f f f 8 f f f 
8 8 8 f f f f 8 f f f f 8 8 . . 
8 8 8 f f f f 8 f f f f 8 . . . 
. . e e e e e . e e e e e . . . 
`, img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b 8 8 f f f f f f f f f 8 f f f 
8 8 f f f f 8 8 8 f f f 8 8 . . 
8 8 f f f 8 8 8 8 8 f f f . . . 
e e e e e . . . . . e e e e e . 
`, img`
. . . . . . . . . . . f f f . . 
. . . . f f f f f f . f b f f . 
. . . f f f f f f f f f f b f . 
. . . f f e e e e f f . f b f f 
. . . f e 1 e e 1 e f . f f b f 
. . . f e e e e e e f . . f b f 
. . . e 2 e e e e 2 . . . f b f 
. . . . e 2 2 2 2 e . . . f b f 
. . 8 8 b e e e e b 8 . . f b f 
. 8 b 8 b b b b b b b 8 . f f f 
. b b b b b b b b b b b b b e f 
b b b b b b b b b b b b b b e f 
b f f f 8 8 8 8 8 f f f 8 f f f 
8 f f f 8 8 8 8 8 f f f 8 8 . . 
8 f f f 8 8 8 8 8 f f f 8 . . . 
. e e e e e . . . e e e e e . . 
`];
            case "myAnim0":
            case "anim2":return [img`
...........fff................
....ffffff.fbff...............
...ffffffffffbf...............
...ffeeeeff.fbff..............
...fe1ee1ef.ffbf..............
...feeeeeef..fbf..............
...e2eeee2...fbf..............
....e2222e...fbf..............
..88beeeeb8..fbf..............
.8b8bbbbbbb8.fff..............
.bbbbbbbbbbbbbef..............
bbbbbbbbbbbbbbef..............
b88ffff8ffff8fff..............
888ffff8ffff88................
888ffff8ffff8.................
..eeeee.eeeee.................
`, img`
..............................
....ffffff....................
...ffffffff...................
...ffeeeeff...................
...fe1ee1ef...................
...feeeeeeff..................
...e2eeee2fbf.................
....e2222efbbf................
..88beeeeb8fbbf...............
.8b8bbbbbbb8ffbf..............
.bbbbbbbbbbbbbef..............
bbbbbbbbbbbbbbef..............
b88ffff8ffff8fff..............
888ffff8ffff88................
888ffff8ffff8.................
..eeeee.eeeee.................
`, img`
..............................
....ffffff....................
...fffffffff..................
...ffeeeeffbf.................
...fe1ee1effbf................
...feeeeeeffbff...............
...e2eeee2f.fbf...............
....e2222ef.fbf...............
..88beeeeb8f.fb...............
.8b8bbbbbbb8ffbf..............
.bbbbbbbbbbbbbef..............
bbbbbbbbbbbbbbef..............
b88ffff8ffff8fff..............
888ffff8ffff88................
888ffff8ffff8.................
..eeeee.eeeee.................
`, img`
..............................
....ffffff....................
...ffffffff...................
...ffeeeeff...................
...fe1ee1ef........ff.........
...feeeeeef......ffff.........
...e2eeee2f....fffbbf.........
....e2222ef...fbbbbff.........
..88beeeeb8f.ffbbbff..........
.8b8bbbbbbb8ffbffff...........
.bbbbbbbbbbbbbef..............
bbbbbbbbbbbbbbef..............
b88ffff8ffff8fff..............
888ffff8ffff88................
888ffff8ffff8.................
..eeeee.eeeee.................
`, img`
...........fff................
....ffffff.fbff...............
...ffffffffffbf...............
...ffeeeeff.fbff..............
...fe1ee1ef.ffbf..............
...feeeeeef..fbf..............
...e2eeee2...fbf..............
....e2222e...fbf..............
..88beeeeb8..fbf..............
.8b8bbbbbbb8.fff..............
.bbbbbbbbbbbbbef..............
bbbbbbbbbbbbbbef..............
b88ffff8ffff8fff..............
888ffff8ffff88................
888ffff8ffff8.................
..eeeee.eeeee.................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
